apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  serviceAccountName: iam-trello
  containers:
  - name: test-pod
    image: amazon/aws-cli
    command: [ "sleep" ]
    args: [ "infinity" ]
    ports:
      - containerPort: 80
        name: http-web-svc